[pytest]
DJANGO_SETTINGS_MODULE = hope_ams.config.settings
testpaths = tests
pythonpath = tests/_extras
python_files = test_*.py
addopts =
    --tb short
    --cov src
    --cov-config=tests/.coveragerc
    --cov-report xml:coverage.xml
markers =
    admin: Smoke test for admin site
    smoke: Generic smoke test
    skip_models: Skip specific models from admin smoke test
    skip_buttons: Skip specific admin buttons from smoke test
