[tox]
requires =
    tox>=4.2
    tox-uv>=1.25
env_list =
    lint
    mypy
    tests
    pkg_meta
skip_missing_interpreters = true

[testenv]
runner = uv-venv-lock-runner
base_python = python3.14
skip_install = true
pass_env =
    CACHE_URL
    DATABASE_URL
    HOPE_API_TOKEN
    HOPE_API_URL
    PYTHONDONTWRITEBYTECODE
    PYTHONPATH
    USER
set_env =
    HOPE_API_TOKEN = dev-ams-api-key-change-in-production
    PYTHONDONTWRITEBYTECODE = true
    PYTHONPATH = {toxinidir}/src
    SECRET_KEY = super_secret_key_just_for_testing
commands =
    {posargs:pytest tests -rw}
dependency_groups = dev

[testenv:lint]
description = run static analysis and style check using ruff
skip_install = true
deps =
    pre-commit-uv>=4.1.1
commands =
    pre-commit run --all-files --show-diff-on-failure

[testenv:mypy]
runner = uv-venv-lock-runner
description = run mypy type checking
skip_install = false
commands =
    mypy --config-file mypy.ini {posargs:}
dependency_groups = mypy
uv_sync_flags = --no-editable

[testenv:tests]
description = run test suite with pytest
skip_install = false
deps =
    pip
    uv
commands =
    pytest {posargs:tests -rw -n auto --dist=loadgroup}
    diff-cover coverage.xml --compare-branch=develop --fail-under=0
dependency_groups =
    dev

[testenv:pkg_meta]
skip_install = true
deps =
    build
    twine
commands =
    uv build --sdist -q --out-dir {env_tmp_dir} .
    uvx twine check {env_tmp_dir}{/}*
    uv pip install --no-binary hope_ams --find-links {env_tmp_dir} hope_ams

[testenv:semgrep]
runner = uv-venv-lock-runner
description = run semgrep
skip_install = false
commands =
    semgrep \
      scan \
      --exclude=.semgrep/ \
      --exclude=docs/_scripts/ \
      --error \
      --disable-version-check \
      .
allowlist_externals =
    semgrep
dependency_groups = mypy
uv_sync_flags = --no-editable

[testenv:security]
description = run mypy type checking
skip_install = true
commands =
    trivy fs \
      --license-full \
      --format table \
      --severity HIGH,CRITICAL \
      --scanners vuln,misconfig,secret,license \
      --list-all-pkgs \
      uv.lock
    bandit -c bandit.yaml -r src/
    uvx pysentry-rs . --fail-on high --compact --display table
    pip-audit -l
allowlist_externals =
    bandit
    docker
    trivy
    uvx
