# Generated by Django 5.2.15 on 2026-07-01 17:05

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import strategy_field.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Office",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "correlation_id",
                    models.UUIDField(
                        help_text="Unique identifier for this office",
                        unique=True,
                        verbose_name="Correlation ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the office",
                        max_length=255,
                        verbose_name="Name",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly version of the office name",
                        verbose_name="Slug",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Office code or identifier",
                        max_length=100,
                        verbose_name="Code",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this office was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When this office was last updated",
                        verbose_name="Updated At",
                    ),
                ),
            ],
            options={
                "verbose_name": "Office",
                "verbose_name_plural": "Offices",
            },
        ),
        migrations.CreateModel(
            name="RuleConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Name of the rule",
                        max_length=255,
                        verbose_name="Name",
                    ),
                ),
                (
                    "rule",
                    strategy_field.fields.StrategyField(
                        blank=True,
                        default=None,
                        help_text="The rule class this configuration applies to",
                        null=True,
                        verbose_name="Rule",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this rule configuration is enabled",
                        verbose_name="Enabled",
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Configuration parameters for this rule",
                        verbose_name="Configuration",
                    ),
                ),
                (
                    "phase",
                    models.CharField(
                        choices=[
                            ("prevention", "Prevention"),
                            ("detection", "Detection"),
                            ("both", "Both"),
                        ],
                        default="both",
                        help_text="Whether this rule applies to prevention or detection phase",
                        max_length=20,
                        verbose_name="Phase",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this rule configuration was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When this rule configuration was last updated",
                        verbose_name="Updated At",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rule Configuration",
                "verbose_name_plural": "Rule Configurations",
            },
        ),
        migrations.CreateModel(
            name="AMSUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={"unique": "A user with that username already exists."},
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(blank=True, max_length=150, verbose_name="first name"),
                ),
                (
                    "last_name",
                    models.CharField(blank=True, max_length=150, verbose_name="last name"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="email address"),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now, verbose_name="date joined"),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="PaymentPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "correlation_id",
                    models.UUIDField(
                        help_text="Unique identifier for this payment plan",
                        unique=True,
                        verbose_name="Correlation ID",
                    ),
                ),
                (
                    "unicef_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="UNICEF identifier for this payment plan",
                        max_length=255,
                        verbose_name="UNICEF ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Current status of the payment plan",
                        max_length=50,
                        verbose_name="Status",
                    ),
                ),
                (
                    "dispersion_start_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date when dispersion started",
                        null=True,
                        verbose_name="Dispersion Start Date",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        blank=True,
                        default="USD",
                        help_text="Currency code for this payment plan",
                        max_length=3,
                        verbose_name="Currency",
                    ),
                ),
                (
                    "total_entitled_quantity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Total quantity entitled in this payment plan",
                        max_digits=16,
                        null=True,
                        verbose_name="Total Entitled Quantity",
                    ),
                ),
                (
                    "delivery_mechanism",
                    models.CharField(
                        blank=True,
                        help_text="Mechanism used for delivering payments",
                        max_length=255,
                        verbose_name="Delivery Mechanism",
                    ),
                ),
                (
                    "financial_service_provider",
                    models.CharField(
                        blank=True,
                        help_text="Provider of the financial service",
                        max_length=255,
                        verbose_name="Financial Service Provider",
                    ),
                ),
                (
                    "reconciliation_window_in_days",
                    models.IntegerField(
                        blank=True,
                        help_text="Number of days for reconciliation window",
                        null=True,
                        verbose_name="Reconciliation Window (days)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this payment plan was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When this payment plan was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "office",
                    models.ForeignKey(
                        help_text="The office this payment plan is associated with",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_plans",
                        to="hope_ams.office",
                        verbose_name="Office",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Plan",
                "verbose_name_plural": "Payment Plans",
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("correlation_id", models.UUIDField(unique=True)),
                (
                    "individual_id",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("currency", models.CharField(max_length=255)),
                (
                    "fsp",
                    models.CharField(help_text="financial service provider", max_length=255),
                ),
                (
                    "delivery_type",
                    models.CharField(help_text="DeliveryMechanism", max_length=255),
                ),
                ("unicef_id", models.CharField(blank=True, max_length=255)),
                ("household_id", models.UUIDField(blank=True, null=True)),
                ("household_unicef_id", models.CharField(blank=True, max_length=255)),
                ("status", models.CharField(blank=True, default="", max_length=100)),
                (
                    "entitlement_source",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
                ),
                ("vulnerability_score", models.FloatField(blank=True, null=True)),
                ("excluded", models.BooleanField(default=False)),
                ("conflicted", models.BooleanField(default=False)),
                ("order_number", models.IntegerField(blank=True, null=True)),
                ("token_number", models.CharField(blank=True, max_length=255)),
                ("current_household_data", models.JSONField(blank=True, null=True)),
                (
                    "entitlement_quantity",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
                ),
                (
                    "entitlement_quantity_usd",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
                ),
                ("entitlement_date", models.DateTimeField(blank=True, null=True)),
                (
                    "delivered_quantity",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
                ),
                (
                    "delivered_quantity_usd",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
                ),
                ("delivery_date", models.DateTimeField(blank=True, null=True)),
                ("snapshot", models.JSONField(blank=True, default=dict)),
                ("errors", models.JSONField(blank=True, default=dict)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="hope_ams.paymentplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment",
                "verbose_name_plural": "Payment Plans",
            },
        ),
        migrations.CreateModel(
            name="Programme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "correlation_id",
                    models.UUIDField(
                        help_text="Unique identifier for this programme",
                        unique=True,
                        verbose_name="Correlation ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the programme",
                        max_length=255,
                        verbose_name="Name",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Programme code or identifier",
                        max_length=100,
                        verbose_name="Code",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this programme was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When this programme was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "office",
                    models.ForeignKey(
                        help_text="Office this programme belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programmes",
                        to="hope_ams.office",
                        verbose_name="Office",
                    ),
                ),
            ],
            options={
                "verbose_name": "Programme",
                "verbose_name_plural": "Programmes",
            },
        ),
        migrations.AddField(
            model_name="paymentplan",
            name="programme",
            field=models.ForeignKey(
                help_text="The programme this payment plan belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_plans",
                to="hope_ams.programme",
                verbose_name="Programme",
            ),
        ),
        migrations.CreateModel(
            name="DetectionRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phase",
                    models.CharField(
                        choices=[
                            ("prevention", "Prevention"),
                            ("detection", "Detection"),
                        ],
                        help_text="The phase of the detection run (prevention or detection)",
                        max_length=20,
                        verbose_name="Phase",
                    ),
                ),
                (
                    "trigger",
                    models.CharField(
                        choices=[("api", "API"), ("manual", "Manual")],
                        help_text="How the detection run was triggered",
                        max_length=20,
                        verbose_name="Trigger",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        help_text="Current status of the detection run",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "rules_executed",
                    models.IntegerField(
                        default=0,
                        help_text="Number of rules executed in this detection run",
                        verbose_name="Rules Executed",
                    ),
                ),
                (
                    "anomalies_found",
                    models.IntegerField(
                        default=0,
                        help_text="Number of anomalies detected",
                        verbose_name="Anomalies Found",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the detection run started",
                        verbose_name="Started At",
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the detection run finished",
                        null=True,
                        verbose_name="Finished At",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata for this detection run",
                        verbose_name="Metadata",
                    ),
                ),
                (
                    "office",
                    models.ForeignKey(
                        help_text="The office this detection run is associated with",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hope_ams.office",
                        verbose_name="Office",
                    ),
                ),
                (
                    "payment_plan",
                    models.ForeignKey(
                        help_text="The payment plan this detection run is associated with",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detection_runs",
                        to="hope_ams.paymentplan",
                        verbose_name="Payment Plan",
                    ),
                ),
                (
                    "programme",
                    models.ForeignKey(
                        help_text="The programme this detection run is associated with",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hope_ams.programme",
                        verbose_name="Programme",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detection Run",
                "verbose_name_plural": "Detection Runs",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="AnomalyResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phase",
                    models.CharField(
                        choices=[
                            ("prevention", "Prevention"),
                            ("detection", "Detection"),
                        ],
                        help_text="The phase of the detection run (prevention or detection)",
                        max_length=20,
                        verbose_name="Phase",
                    ),
                ),
                (
                    "rule_name",
                    models.CharField(
                        db_index=True,
                        help_text="Name of the rule that detected this anomaly",
                        max_length=100,
                        verbose_name="Rule Name",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        db_index=True,
                        help_text="Severity level of this anomaly",
                        max_length=20,
                        verbose_name="Severity",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("reviewing", "Reviewing"),
                            ("dismissed", "Dismissed"),
                            ("confirmed", "Confirmed"),
                        ],
                        db_index=True,
                        default="open",
                        help_text="Current status of this anomaly",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Brief title describing the anomaly",
                        max_length=255,
                        verbose_name="Title",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of the anomaly",
                        verbose_name="Description",
                    ),
                ),
                (
                    "object_type",
                    models.CharField(
                        choices=[
                            ("household", "Household"),
                            ("individual", "Individual"),
                            ("payment", "Payment"),
                            ("payment_plan", "Payment Plan"),
                        ],
                        help_text="Type of object this anomaly relates to",
                        max_length=50,
                        verbose_name="Object Type",
                    ),
                ),
                (
                    "object_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="Unique identifier for the object",
                        verbose_name="Object ID",
                    ),
                ),
                (
                    "object_unicef_id",
                    models.CharField(
                        blank=True,
                        help_text="UNICEF identifier for the object",
                        max_length=255,
                        verbose_name="UNICEF ID",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata for this anomaly",
                        verbose_name="Metadata",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this anomaly result was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When this anomaly result was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "detection_run",
                    models.ForeignKey(
                        help_text="The detection run this anomaly belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anomalies",
                        to="hope_ams.detectionrun",
                        verbose_name="Detection Run",
                    ),
                ),
                (
                    "office",
                    models.ForeignKey(
                        help_text="The office where the anomaly was detected",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hope_ams.office",
                        verbose_name="Office",
                    ),
                ),
                (
                    "payment_plan",
                    models.ForeignKey(
                        help_text="The payment plan related to this anomaly",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hope_ams.paymentplan",
                        verbose_name="Payment Plan",
                    ),
                ),
                (
                    "programme",
                    models.ForeignKey(
                        help_text="The programme associated with the anomaly",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hope_ams.programme",
                        verbose_name="Programme",
                    ),
                ),
            ],
            options={
                "verbose_name": "Anomaly Result",
                "verbose_name_plural": "Anomaly Results",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProgrammeRuleConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Name of the programme rule configuration",
                        max_length=255,
                        verbose_name="Name",
                    ),
                ),
                (
                    "rule",
                    strategy_field.fields.StrategyField(
                        blank=True,
                        default=None,
                        help_text="The rule class this configuration applies to",
                        null=True,
                        verbose_name="Rule",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this rule configuration is enabled",
                        verbose_name="Enabled",
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Configuration parameters for this rule in the programme context",
                        verbose_name="Configuration",
                    ),
                ),
                (
                    "phase",
                    models.CharField(
                        choices=[
                            ("prevention", "Prevention"),
                            ("detection", "Detection"),
                            ("both", "Both"),
                        ],
                        default="both",
                        help_text="Whether this rule applies to prevention or detection phase",
                        max_length=20,
                        verbose_name="Phase",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this configuration was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When this configuration was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "programme",
                    models.ForeignKey(
                        help_text="The programme this configuration applies to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programme_rule_configurations",
                        to="hope_ams.programme",
                        verbose_name="Programme",
                    ),
                ),
            ],
            options={
                "verbose_name": "Programme Rule Configuration",
                "verbose_name_plural": "Programme Rule Configurations",
            },
        ),
        migrations.CreateModel(
            name="UserRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "expires",
                    models.DateField(
                        blank=True,
                        help_text="Date when this role expires",
                        null=True,
                        verbose_name="Expiration Date",
                    ),
                ),
                (
                    "country_office",
                    models.ForeignKey(
                        help_text="The office this role is associated with",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_roles",
                        to="hope_ams.office",
                        verbose_name="Office",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        help_text="The group this role belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auth.group",
                        verbose_name="Group",
                    ),
                ),
                (
                    "programme",
                    models.ForeignKey(
                        blank=True,
                        help_text="The programme this role is associated with (if any)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hope_ams.programme",
                        verbose_name="Programme",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user associated with this role",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Role",
                "verbose_name_plural": "User Roles",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "country_office", "group"),
                        name="detection_userrole_unique_role",
                    )
                ],
            },
        ),
    ]
