# Generated by Django 5.2.15 on 2026-07-04 07:47

import django.db.models.deletion
import hope_ams.models.anomaly_result
import hope_ams.models.detection_run
import hope_ams.models.programme_rule_configuration
import hope_ams.models.rule_config
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hope_ams", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="amsuser",
            options={},
        ),
        migrations.AlterModelOptions(
            name="office",
            options={"ordering": ("name",), "verbose_name": "Office", "verbose_name_plural": "Offices"},
        ),
        migrations.AlterModelOptions(
            name="payment",
            options={"verbose_name": "Payment", "verbose_name_plural": "Payments"},
        ),
        migrations.AlterModelOptions(
            name="programme",
            options={"ordering": ("name",), "verbose_name": "Programme", "verbose_name_plural": "Programmes"},
        ),
        migrations.AddField(
            model_name="amsuser",
            name="azure_id",
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="amsuser",
            name="display_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="amsuser",
            name="job_title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="anomalyresult",
            name="object_type",
            field=models.CharField(
                choices=hope_ams.models.anomaly_result.get_anomaly_result_object_types,
                help_text="Type of object this anomaly relates to",
                max_length=50,
                verbose_name="Object Type",
            ),
        ),
        migrations.AlterField(
            model_name="anomalyresult",
            name="phase",
            field=models.CharField(
                choices=hope_ams.models.anomaly_result.get_anomaly_result_phases,
                help_text="The phase of the detection run (prevention or detection)",
                max_length=20,
                verbose_name="Phase",
            ),
        ),
        migrations.AlterField(
            model_name="anomalyresult",
            name="severity",
            field=models.CharField(
                choices=hope_ams.models.anomaly_result.get_anomaly_result_severities,
                db_index=True,
                help_text="Severity level of this anomaly",
                max_length=20,
                verbose_name="Severity",
            ),
        ),
        migrations.AlterField(
            model_name="anomalyresult",
            name="status",
            field=models.CharField(
                choices=hope_ams.models.anomaly_result.get_anomaly_result_statuses,
                db_index=True,
                default="open",
                help_text="Current status of this anomaly",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="detectionrun",
            name="phase",
            field=models.CharField(
                choices=hope_ams.models.detection_run.get_detection_run_phases,
                help_text="The phase of the detection run (prevention or detection)",
                max_length=20,
                verbose_name="Phase",
            ),
        ),
        migrations.AlterField(
            model_name="detectionrun",
            name="status",
            field=models.CharField(
                choices=hope_ams.models.detection_run.get_detection_run_statuses,
                default="queued",
                help_text="Current status of the detection run",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="detectionrun",
            name="trigger",
            field=models.CharField(
                choices=hope_ams.models.detection_run.get_detection_run_triggers,
                help_text="How the detection run was triggered",
                max_length=20,
                verbose_name="Trigger",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="conflicted",
            field=models.BooleanField(
                default=False, help_text="Whether this payment has conflicts", verbose_name="Conflicted"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="correlation_id",
            field=models.UUIDField(
                help_text="Unique identifier for this payment", unique=True, verbose_name="Correlation ID"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="currency",
            field=models.CharField(help_text="Currency code for this payment", max_length=255, verbose_name="Currency"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="current_household_data",
            field=models.JSONField(
                blank=True,
                help_text="Current data associated with the household",
                null=True,
                verbose_name="Current Household Data",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="delivered_quantity",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Quantity actually delivered",
                max_digits=15,
                null=True,
                verbose_name="Delivered Quantity",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="delivered_quantity_usd",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Delivered quantity in USD",
                max_digits=15,
                null=True,
                verbose_name="Delivered Quantity (USD)",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="delivery_date",
            field=models.DateTimeField(
                blank=True, help_text="Date when payment was delivered", null=True, verbose_name="Delivery Date"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="delivery_type",
            field=models.CharField(
                help_text="Delivery mechanism for this payment", max_length=255, verbose_name="Delivery Type"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="entitlement_date",
            field=models.DateTimeField(
                blank=True, help_text="Date when entitlement was set", null=True, verbose_name="Entitlement Date"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="entitlement_quantity",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Quantity entitled for this payment",
                max_digits=15,
                null=True,
                verbose_name="Entitlement Quantity",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="entitlement_quantity_usd",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Entitlement quantity in USD",
                max_digits=15,
                null=True,
                verbose_name="Entitlement Quantity (USD)",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="entitlement_source",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Source amount for this entitlement",
                max_digits=16,
                null=True,
                verbose_name="Entitlement Source",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="errors",
            field=models.JSONField(
                blank=True, default=dict, help_text="Errors encountered during processing", verbose_name="Errors"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="excluded",
            field=models.BooleanField(
                default=False, help_text="Whether this payment is excluded", verbose_name="Excluded"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="fsp",
            field=models.CharField(
                help_text="Financial service provider for this payment",
                max_length=255,
                verbose_name="Financial Service Provider",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="household_id",
            field=models.UUIDField(
                blank=True, help_text="Unique identifier for the household", null=True, verbose_name="Household ID"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="household_unicef_id",
            field=models.CharField(
                blank=True,
                help_text="UNICEF identifier for the household",
                max_length=255,
                verbose_name="Household UNICEF ID",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="individual_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Identifier for the individual receiving the payment",
                max_length=255,
                verbose_name="Individual ID",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="order_number",
            field=models.IntegerField(
                blank=True, help_text="Order number for this payment", null=True, verbose_name="Order Number"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="plan",
            field=models.ForeignKey(
                help_text="The payment plan this payment belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="hope_ams.paymentplan",
                verbose_name="Payment Plan",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="snapshot",
            field=models.JSONField(
                blank=True, default=dict, help_text="Snapshot of data at time of processing", verbose_name="Snapshot"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Current status of this payment",
                max_length=100,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="token_number",
            field=models.CharField(
                blank=True, help_text="Token number for this payment", max_length=255, verbose_name="Token Number"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="unicef_id",
            field=models.CharField(
                blank=True, help_text="UNICEF identifier for this payment", max_length=255, verbose_name="UNICEF ID"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="vulnerability_score",
            field=models.FloatField(
                blank=True,
                help_text="Vulnerability score for the recipient",
                null=True,
                verbose_name="Vulnerability Score",
            ),
        ),
        migrations.AlterField(
            model_name="programmeruleconfiguration",
            name="phase",
            field=models.CharField(
                choices=hope_ams.models.programme_rule_configuration.get_programme_rule_config_phases,
                default="prevention",
                help_text="Whether this rule applies to prevention or detection phase",
                max_length=20,
                verbose_name="Phase",
            ),
        ),
        migrations.AlterField(
            model_name="ruleconfig",
            name="phase",
            field=models.CharField(
                choices=hope_ams.models.rule_config.get_rule_config_phases,
                default="prevention",
                help_text="Whether this rule applies to prevention or detection phase",
                max_length=20,
                verbose_name="Phase",
            ),
        ),
        migrations.AlterModelTable(
            name="amsuser",
            table="hope_ams_user",
        ),
    ]
