# Generated by Django 5.2.15 on 2026-06-07 08:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BusinessArea",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Business Area",
                "verbose_name_plural": "Business Areas",
            },
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business_area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programs",
                        to="detections.businessarea",
                    ),
                ),
            ],
            options={
                "verbose_name": "Program",
                "verbose_name_plural": "Programs",
            },
        ),
        migrations.CreateModel(
            name="PaymentPlan",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                (
                    "unicef_id",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business_area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_plans",
                        to="detections.businessarea",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_plans",
                        to="detections.program",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Plan",
                "verbose_name_plural": "Payment Plans",
            },
        ),
        migrations.CreateModel(
            name="DetectionRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "phase",
                    models.CharField(
                        choices=[
                            ("prevention", "Prevention"),
                            ("detection", "Detection"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "trigger",
                    models.CharField(choices=[("api", "API"), ("manual", "Manual")], max_length=20),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("rules_executed", models.IntegerField(default=0)),
                ("anomalies_found", models.IntegerField(default=0)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "business_area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="detections.businessarea",
                    ),
                ),
                (
                    "payment_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detection_runs",
                        to="detections.paymentplan",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="detections.program",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detection Run",
                "verbose_name_plural": "Detection Runs",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="AnomalyResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "phase",
                    models.CharField(
                        choices=[
                            ("prevention", "Prevention"),
                            ("detection", "Detection"),
                        ],
                        max_length=20,
                    ),
                ),
                ("rule_name", models.CharField(db_index=True, max_length=100)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("reviewing", "Reviewing"),
                            ("dismissed", "Dismissed"),
                            ("confirmed", "Confirmed"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "object_type",
                    models.CharField(
                        choices=[
                            ("household", "Household"),
                            ("individual", "Individual"),
                            ("payment", "Payment"),
                            ("payment_plan", "Payment Plan"),
                        ],
                        max_length=50,
                    ),
                ),
                ("object_id", models.UUIDField(db_index=True)),
                ("object_unicef_id", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business_area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="detections.businessarea",
                    ),
                ),
                (
                    "detection_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anomalies",
                        to="detections.detectionrun",
                    ),
                ),
                (
                    "payment_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="detections.paymentplan",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="detections.program",
                    ),
                ),
            ],
            options={
                "verbose_name": "Anomaly Result",
                "verbose_name_plural": "Anomaly Results",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RuleConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rule_name", models.CharField(db_index=True, max_length=100)),
                ("enabled", models.BooleanField(default=True)),
                ("config", models.JSONField(blank=True, default=dict)),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("global", "Global"),
                            ("business_area", "Business Area"),
                            ("program", "Program"),
                            ("payment_plan", "Payment Plan"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business_area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="detections.businessarea",
                    ),
                ),
                (
                    "payment_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="detections.paymentplan",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="detections.program",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rule Configuration",
                "verbose_name_plural": "Rule Configurations",
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "rule_name",
                            "scope",
                            "business_area",
                            "program",
                            "payment_plan",
                        ),
                        name="unique_rule_config_per_scope",
                    )
                ],
            },
        ),
    ]
