from ..registry import registry

from .data_changed_after_approval import DataChangedAfterApprovalRule
from .delivered_vs_received_mismatch import DeliveredVsReceivedMismatchRule
from .distributed_but_not_delivered import DistributedButNotDeliveredRule
from .duplicate_payment_same_cycle import DuplicatePaymentSameCycleRule
from .empty_household_active import EmptyHouseholdActiveRule
from .fsp_high_failure_rate import FspHighFailureRateRule
from .partial_delivery_pattern import PartialDeliveryPatternRule
from .payment_amount_hh_size_mismatch import PaymentAmountHhSizeMismatchRule
from .pending_payment_stale import PendingPaymentStaleRule
from .pwd_prevalence_outlier import PwdPrevalenceOutlierRule
from .reconciliation_overdue import ReconciliationOverdueRule
from .registration_date_anomaly import RegistrationDateAnomalyRule
from .unrealistic_sex_ratio import UnrealisticSexRatioRule
from .unusual_payment_timing import UnusualPaymentTimingRule
from .withdrawn_hh_in_active_plan import WithdrawnHhInActivePlanRule

registry.register(DeliveredVsReceivedMismatchRule)
registry.register(FspHighFailureRateRule)
registry.register(DuplicatePaymentSameCycleRule)
registry.register(PaymentAmountHhSizeMismatchRule)
registry.register(DataChangedAfterApprovalRule)
registry.register(WithdrawnHhInActivePlanRule)
registry.register(ReconciliationOverdueRule)
registry.register(PendingPaymentStaleRule)
registry.register(PartialDeliveryPatternRule)
registry.register(DistributedButNotDeliveredRule)
registry.register(UnrealisticSexRatioRule)
registry.register(PwdPrevalenceOutlierRule)
registry.register(EmptyHouseholdActiveRule)
registry.register(RegistrationDateAnomalyRule)
registry.register(UnusualPaymentTimingRule)
