name: "MYPY"

on:
  workflow_call:

permissions:
  contents: read

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - uses: astral-sh/setup-uv@v7

      - name: Install dependencies
        run: uv sync --frozen

      - name: Run mypy
        run: uv run tox -e mypy
